describe('next-touched-pages', () => {
  describe('generateCommentMarkdown', () => {
    beforeEach(() => {
      jest.resetModules()
    })

    it('generates a comment when changedPages is empty', async () => {
      const { generateCommentMarkdown } = await import('../')
      expect(generateCommentMarkdown([], {})).toBe(`<h2>Changed Pages</h2>
<br>
This PR doesn't appear to affect any pages.<br>
This comment was generated by <a href="https://github.com/hashicorp/web-platform-packages/tree/main/packages/tools/scripts/next-touched-pages"><code>next-touched-pages</code></a> and isn't guaranteed to be accurate.<br>
<!-- __NEXTJS_TOUCHED_PAGES -->`)
    })

    it('generates a comment with a basic page', async () => {
      const { generateCommentMarkdown } = await import('../')
      expect(
        generateCommentMarkdown(['/'], {
          baseBranch: 'main',
          branch: 'feature',
        })
      ).toBe(`<h2>Changed Pages</h2>
<table><tr><th>Page</th><th><code>main</code></th><th><code>feature</code></th></tr><tr><td><code>/</code></td><td><li><code>/</code></li></td><td><li><code>/</code></li></td></tr></table>
<br>
This comment was generated by <a href="https://github.com/hashicorp/web-platform-packages/tree/main/packages/tools/scripts/next-touched-pages"><code>next-touched-pages</code></a> and isn't guaranteed to be accurate.<br>
<!-- __NEXTJS_TOUCHED_PAGES -->`)
    })

    it('generates a comment with a dynamic page', async () => {
      const { generateCommentMarkdown } = await import('../')
      expect(
        generateCommentMarkdown(['/[page]'], {
          baseBranch: 'main',
          branch: 'feature',
          dynamicPathsConfig: {
            '/[page]': ['/one', '/two'],
          },
          urlBuilderConfig: (branch: string) => {
            return `http://${branch}-test.example`
          },
        })
      ).toBe(`<h2>Changed Pages</h2>
<table><tr><th>Page</th><th><code>main</code></th><th><code>feature</code></th></tr><tr><td><code>/[page]</code></td><td><li><a href="http://main-test.example/one"><code>/one</code> #1</a></li><li><a href="http://main-test.example/two"><code>/two</code> #2</a></li></td><td><li><a href="http://feature-test.example/one"><code>/one</code> #1</a></li><li><a href="http://feature-test.example/two"><code>/two</code> #2</a></li></td></tr></table>
<br>
This comment was generated by <a href="https://github.com/hashicorp/web-platform-packages/tree/main/packages/tools/scripts/next-touched-pages"><code>next-touched-pages</code></a> and isn't guaranteed to be accurate.<br>
<!-- __NEXTJS_TOUCHED_PAGES -->`)
    })
  })
})
